//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGestao.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegDetails", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceGestaoClientes")]
    [System.SerializableAttribute()]
    public partial class RegDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CPFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SituacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CPF {
            get {
                return this.CPFField;
            }
            set {
                if ((object.ReferenceEquals(this.CPFField, value) != true)) {
                    this.CPFField = value;
                    this.RaisePropertyChanged("CPF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sexo {
            get {
                return this.SexoField;
            }
            set {
                if ((object.ReferenceEquals(this.SexoField, value) != true)) {
                    this.SexoField = value;
                    this.RaisePropertyChanged("Sexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Situacao {
            get {
                return this.SituacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.SituacaoField, value) != true)) {
                    this.SituacaoField = value;
                    this.RaisePropertyChanged("Situacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertUserRegDetails", ReplyAction="http://tempuri.org/IService1/InsertUserRegDetailsResponse")]
        string InsertUserRegDetails(WebApplicationGestao.ServiceReference1.RegDetails regdet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertUserRegDetails", ReplyAction="http://tempuri.org/IService1/InsertUserRegDetailsResponse")]
        System.Threading.Tasks.Task<string> InsertUserRegDetailsAsync(WebApplicationGestao.ServiceReference1.RegDetails regdet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserRegDetails", ReplyAction="http://tempuri.org/IService1/GetUserRegDetailsResponse")]
        System.Data.DataSet GetUserRegDetails();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserRegDetails", ReplyAction="http://tempuri.org/IService1/GetUserRegDetailsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetUserRegDetailsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FetchUpdatedRecords", ReplyAction="http://tempuri.org/IService1/FetchUpdatedRecordsResponse")]
        System.Data.DataSet FetchUpdatedRecords(WebApplicationGestao.ServiceReference1.RegDetails regdet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FetchUpdatedRecords", ReplyAction="http://tempuri.org/IService1/FetchUpdatedRecordsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> FetchUpdatedRecordsAsync(WebApplicationGestao.ServiceReference1.RegDetails regdet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateUserRegDetails", ReplyAction="http://tempuri.org/IService1/UpdateUserRegDetailsResponse")]
        string UpdateUserRegDetails(WebApplicationGestao.ServiceReference1.RegDetails regdet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateUserRegDetails", ReplyAction="http://tempuri.org/IService1/UpdateUserRegDetailsResponse")]
        System.Threading.Tasks.Task<string> UpdateUserRegDetailsAsync(WebApplicationGestao.ServiceReference1.RegDetails regdet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteUserRegDetails", ReplyAction="http://tempuri.org/IService1/DeleteUserRegDetailsResponse")]
        bool DeleteUserRegDetails(WebApplicationGestao.ServiceReference1.RegDetails regdet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteUserRegDetails", ReplyAction="http://tempuri.org/IService1/DeleteUserRegDetailsResponse")]
        System.Threading.Tasks.Task<bool> DeleteUserRegDetailsAsync(WebApplicationGestao.ServiceReference1.RegDetails regdet);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WebApplicationGestao.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WebApplicationGestao.ServiceReference1.IService1>, WebApplicationGestao.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string InsertUserRegDetails(WebApplicationGestao.ServiceReference1.RegDetails regdet) {
            return base.Channel.InsertUserRegDetails(regdet);
        }
        
        public System.Threading.Tasks.Task<string> InsertUserRegDetailsAsync(WebApplicationGestao.ServiceReference1.RegDetails regdet) {
            return base.Channel.InsertUserRegDetailsAsync(regdet);
        }
        
        public System.Data.DataSet GetUserRegDetails() {
            return base.Channel.GetUserRegDetails();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetUserRegDetailsAsync() {
            return base.Channel.GetUserRegDetailsAsync();
        }
        
        public System.Data.DataSet FetchUpdatedRecords(WebApplicationGestao.ServiceReference1.RegDetails regdet) {
            return base.Channel.FetchUpdatedRecords(regdet);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> FetchUpdatedRecordsAsync(WebApplicationGestao.ServiceReference1.RegDetails regdet) {
            return base.Channel.FetchUpdatedRecordsAsync(regdet);
        }
        
        public string UpdateUserRegDetails(WebApplicationGestao.ServiceReference1.RegDetails regdet) {
            return base.Channel.UpdateUserRegDetails(regdet);
        }
        
        public System.Threading.Tasks.Task<string> UpdateUserRegDetailsAsync(WebApplicationGestao.ServiceReference1.RegDetails regdet) {
            return base.Channel.UpdateUserRegDetailsAsync(regdet);
        }
        
        public bool DeleteUserRegDetails(WebApplicationGestao.ServiceReference1.RegDetails regdet) {
            return base.Channel.DeleteUserRegDetails(regdet);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteUserRegDetailsAsync(WebApplicationGestao.ServiceReference1.RegDetails regdet) {
            return base.Channel.DeleteUserRegDetailsAsync(regdet);
        }
    }
}
